"""Refactor wishlist-user many-to-many

Revision ID: 038a17f77709
Revises: b09a57a4b908
Create Date: 2025-08-21 17:10:26.936941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038a17f77709'
down_revision: Union[str, Sequence[str], None] = 'b09a57a4b908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'shared_with', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shared_with', type_='foreignkey')
    # ### end Alembic commands ###
