"""Add date_of_birth to user_profiles

Revision ID: 2affd04a960d
Revises: 038a17f77709
Create Date: 2025-09-21 12:20:38.624605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2affd04a960d'
down_revision: Union[str, Sequence[str], None] = '038a17f77709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_of_birth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'date_of_birth')
    # ### end Alembic commands ###
